Repository microsoft/quilla, pull requests merged in 2021-07, with the labels that each got.

#18 new: added logging
  src/pytest_quilla/pytest_classes.py
  src/quilla/__init__.py
  src/quilla/browser/browser_validations.py
  src/quilla/ctx.py
  src/quilla/hookspecs/configuration.py
  src/quilla/plugins.py
  src/quilla/reports/__init__.py
  src/quilla/steps/__init__.py
  src/quilla/steps/base_steps.py
  src/quilla/steps/outputs.py
  src/quilla/steps/steps_aggregator.py
  src/quilla/steps/validations.py
  src/quilla/ui_validation.py
  tests/conftest.py
Labels: enhancement

#26 chg: document parser post plugin run
  docs/usage.rst
  src/quilla/_doc.py
Labels: documentation

#25 fix: fixed doc pipeline and changelog generation
  .github/workflows/release-pipeline.yml
  CHANGELOG.md
  VERSION
Labels: CI/CD, documentation

#39 new: added logic for visualparity validation
  setup.py
  src/quilla/common/enums.py
  src/quilla/common/utils.py
  src/quilla/hookspecs/steps.py
  src/quilla/steps/validations/xpath.py
Labels: enhancement

#40 new: added run_id to reports and to the ctx object
  src/pytest_quilla/__init__.py
  src/pytest_quilla/pytest_classes.py
  src/quilla/__init__.py
  src/quilla/ctx.py
  src/quilla/reports/base_report.py
  src/quilla/reports/report_summary.py
  src/quilla/reports/visual_parity_report.py
  src/quilla/ui_validation.py
  tests/conftest.py
Labels: enhancement

#44 new: added blob storage plugin
  .github/workflows/test-pipeline.yml
  .pre-commit-config.yaml
  docs/source/quilla.plugins.rst
  docs/source/quilla.steps.rst
  docs/source/quilla.steps.validations.rst
  images/baselines/TrialCompleteBanner.png
  setup.py
  src/pytest_quilla/pytest_classes.py
  src/quilla/__init__.py
  src/quilla/plugins/__init__.py
  src/quilla/plugins/base_storage.py
  src/quilla/plugins/blob_storage.py
Labels: enhancement

#51 fix: reverted to LocalStorage for VP integration test
  .github/workflows/test-pipeline.yml
  images/baselines/TrialCompleteBanner.png
  images/baselines/snapshots/TrialCompleteBanner_3acf772a-caff-452a-8a71-c7dcf257a366.png
Labels: CI/CD, bug

#50 Fixed example "Validation.json" in README.md
  README.md
Labels: bug, documentation

#53 new: added visual parity documentation
  VERSION
  docs/validation_files.md
  docs/visual_parity.md
  images/baselines/snapshots/TrialCompleteBanner_8a2a1460-2e1e-46a7-8f79-ccb980c5ea89.png
  src/quilla/__init__.py
  src/quilla/ctx.py
  src/quilla/steps/base_steps.py
  src/quilla/steps/steps_aggregator.py
  src/quilla/steps/validations/xpath.py
Labels: documentation, enhancement

#56 new: implemented exclusion XPath feature
  .github/workflows/test-pipeline.yml
  VERSION
  docs/cookbook.md
  docs/index.rst
  docs/validation_files.md
  docs/visual_parity.md
  images/baselines/WholePage.png
  images/baselines/snapshots/TrialCompleteBanner_8a2a1460-2e1e-46a7-8f79-ccb980c5ea89.png
  src/quilla/__init__.py
  src/quilla/steps/base_steps.py
  src/quilla/steps/validations/visual_parity.py
  src/quilla/steps/validations/xpath.py
  tests/integration/test_visual_parity.json
Labels: enhancement
